#:kivy 1.8.0

<KivytestScreen>:
  RelativeLayout:
    size_hint: (.75, 1)
    Image:
      id: image
    Label:
      id: print_label
      text: 'Bild wird gedruckt'
      opacity: 0.0
      font_size: '40sp'
      bold: True
  BoxLayout:
    orientation: 'vertical'
    size_hint: (.25, 1)
    Button:
      id: prev_button
      text: 'Zurück'
    Button:
      id: print_button
      text: 'Drucken'
    Button:
      id: next_button
      text: 'Vorwärts'
